buildscript {
    repositories {
        mavenCentral()
        maven {
            name = 'forge'
            url = 'https://maven.minecraftforge.net/'
        }
    }
    dependencies {
        classpath 'com.github.GTNewHorizons:ForgeGradle:1.2.11'
    }
}

apply plugin: 'forge'

group = 'com.glowingfederal.worldeditoverdrive'
version = '1.0.0'
archivesBaseName = 'WorldEditOverdrive'

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    // Plain Maven syntax is required by this ForgeGradle/Gradle generation.
    maven { url = 'https://www.cursemaven.com' }
}

dependencies {
    // WorldEdit Enhanced is supplied as a separate mod at runtime.
    compile 'curse.maven:worldedit-legacy-enhanced-1135144:5879351'
}

minecraft {
    version = '1.7.10-10.13.4.1614-1.7.10'
    runDir = 'run'
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mcVersion', project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': project.version, 'mcVersion': project.minecraft.version
    }
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}
